name: Reports

on:
  workflow_run:
    workflows: [.NET]
    types: [completed, requested]

jobs:
  vars:
    name: Get run information
    runs-on: ubuntu-latest
    outputs:
      run_info: ${{ toJSON(steps.run_info.outputs) }}
      is_pr: ${{ steps.run_info.outputs.sourceEvent == 'pull_request' }}
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Get information about the source run
        id: run_info
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(echo '${{ steps.run_info.outputs.targetCommitSha }}' | cut -c1-7)"
  before-run:
    name: Before Run
    needs: [vars]
    if: ${{ github.event.action == 'requested' && fromJSON(needs.vars.outputs.is_pr) }}
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PROJECT_NAME: waw-backend-cs-livingdoc
    steps:
      - uses: actions/checkout@v3
      - name: Create body for pull request comment (initial edit)
        id: summary
        uses: actions/github-script@v6
        env:
          COMMIT_SHA: ${{ fromJSON(needs.vars.outputs.run_info).targetCommitSha }}
          IS_INITIAL_EDIT: true
        with:
          result-encoding: string
          script: |
            const script = require('./.github/utils/cloudflare-summary.js');
            return await script({ context, core });
      - name: Find previous comment on pull request
        id: fc
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ fromJSON(needs.vars.outputs.run_info).pullRequestNumber }}
          comment-author: dalbitresb12-bot
          body-includes: Cloudflare Pages
      - name: Create or update comment on pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ fromJSON(needs.vars.outputs.run_info).pullRequestNumber }}
          body: ${{ steps.summary.outputs.result }}
          edit-mode: replace
  livingdoc-deploy:
    name: Deploy LivingDoc to Cloudflare Pages
    needs: [vars]
    if: ${{ github.event.action == 'completed' }}
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Starter.API
      CLOUDFLARE_PROJECT_NAME: waw-backend-cs-livingdoc
    outputs:
      deployment: ${{ toJSON(steps.cloudflare.outputs) }}
    steps:
      - name: Download LivingDoc artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ env.PROJECT_NAME }}.Tests-LivingDoc-${{ runner.os }}-${{ needs.vars.outputs.sha_short }}
      - name: Move LivingDoc to output directory
        run: |
          mkdir dist
          mv LivingDoc.html dist/index.html
      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  publish_report:
    name: Publish test report
    needs: [vars]
    if: ${{ github.event.action == 'completed' }}
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Starter.API
    outputs:
      report: ${{ toJSON(steps.report.outputs) }}
    steps:
      - name: Publish test report
        id: report
        uses: dorny/test-reporter@v1
        with:
          artifact: ${{ env.PROJECT_NAME }}.Tests-${{ runner.os }}-${{ needs.vars.outputs.sha_short }}
          name: Test Results
          path: "*.trx"
          reporter: dotnet-trx
          fail-on-error: "false"
  after_run:
    name: After Run
    needs: [vars, livingdoc-deploy, publish_report]
    if: ${{ github.event.action == 'completed' }}
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PROJECT_NAME: waw-backend-cs-livingdoc
    steps:
      - uses: actions/checkout@v3
      - name: Publish status to job summary and generate pull request comment
        id: summary
        env:
          COMMIT_SHA: ${{ fromJSON(needs.vars.outputs.run_info).targetCommitSha }}
          TEST_REPORT: ${{ needs.publish_report.outputs.report }}
          RUN_INFO: ${{ needs.vars.outputs.run_info }}
          CLOUDFLARE: ${{ needs.livingdoc-deploy.outputs.deployment }}
          BUILD_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./.github/utils/cloudflare-summary.js');
            return await script({ context, core });
      - name: Find previous comment on pull request
        id: fc
        if: ${{ fromJSON(needs.vars.outputs.is_pr) }}
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ fromJSON(needs.vars.outputs.run_info).pullRequestNumber }}
          comment-author: dalbitresb12-bot
          body-includes: Cloudflare Pages
      - name: Create or update comment on pull request
        if: ${{ fromJSON(needs.vars.outputs.is_pr) }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ fromJSON(needs.vars.outputs.run_info).pullRequestNumber }}
          body: ${{ steps.summary.outputs.result }}
          edit-mode: replace
